name: Snapshot build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - armv7hf
          - aarch64
    container: axisecp/acap-native-sdk:12.1.0-${{ matrix.arch }}-ubuntu24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build ACAP
        working-directory: app/
        run: |
          . /opt/axis/acapsdk/environment-setup*
          acap-build .
      - name: Persist Artifacts
        uses: actions/upload-artifact@v4.5.0
        with:
          name: build-${{ matrix.arch }}
          path: "app/*.eap"
